# fly.toml app configuration file generated for vlcn-rest-litefs on 2023-09-09T20:16:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vlcn-rest-litefs"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = "8080"
  PRIMARY_REGION = "iad"

[[mounts]]
  source = "litefs"
  destination = "/var/lib/litefs"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
